# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Load < Formula
  desc "Styra Load is an enterprise-grade authorization engine built to provide resource-efficient performance for data-heavy workloads"
  homepage "https://www.styra.com/styra-load"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StyraInc/load/releases/download/v1.4.0/load_Darwin_x86_64"
      sha256 "b035a4dfb0a5c83b2bb40ea74e42792c2eb9a0b266b256d01b2126e31f9a9d0e"

      def install
        bin.install "load_Darwin_x86_64" => "load"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StyraInc/load/releases/download/v1.4.0/load_Darwin_arm64"
      sha256 "c59e3e4abcb1f05e9d5002ca185911f2074a9fb933d6db2cd62122eb396abca8"

      def install
        bin.install "load_Darwin_arm64" => "load"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/StyraInc/load/releases/download/v1.4.0/load_Linux_x86_64"
      sha256 "d39e202b17160615ceed936771388387874e117088ad3b6fd87aebafcb124519"

      def install
        bin.install "load_Linux_x86_64" => "load"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StyraInc/load/releases/download/v1.4.0/load_Linux_arm64"
      sha256 "22ad39e40fd1ba7faa9734271e6cbf297a03eea077defe390e764d0e30e8dc23"

      def install
        bin.install "load_Linux_arm64" => "load"
      end
    end
  end
end
