# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Regal < Formula
  desc "Regal is a linter for Rego, with the goal of making your Rego magnificent!"
  homepage "https://github.com/styrainc/regal"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StyraInc/regal/releases/download/v0.1.1/regal_Darwin_x86_64"
      sha256 "ac9dc049374928484bca8654a394c8694a70ab0efd27fdc79a03e38cb3b4826b"

      def install
        bin.install "regal_Darwin_x86_64" => "regal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StyraInc/regal/releases/download/v0.1.1/regal_Darwin_arm64"
      sha256 "ed179fa121adc000ed4db48d5055ca9826bd9457b0d0c4866df82e78431d222b"

      def install
        bin.install "regal_Darwin_arm64" => "regal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StyraInc/regal/releases/download/v0.1.1/regal_Linux_arm64"
      sha256 "b1dc90dabbebecef9baba37013ed9ea9b81bd6157a631615591130dffddf9263"

      def install
        bin.install "regal_Linux_arm64" => "regal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/StyraInc/regal/releases/download/v0.1.1/regal_Linux_x86_64"
      sha256 "3e2da4db38bdfd2f8a3a2e7a9e87fcdb2bcbcd5fc675301cec0ada55280b5eff"

      def install
        bin.install "regal_Linux_x86_64" => "regal"
      end
    end
  end
end
